<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="bblanchon.PDFium.Win32" Version="155.0.8057" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="LitePdf.Core.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LitePdf.Core\LitePdf.Core.csproj" />
  </ItemGroup>

</Project>
